[package]
name = "wasps"
version = "0.1.0"
edition = "2021"
default-run = "server"

[[bin]]
name = "implant"

[[bin]]
name = "server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
